<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.vitalylitvinov74</groupId>
        <artifactId>java-message-bus</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>messaging-api</artifactId>
    <name>messaging-api</name>
    <description>Контракты шины для прикладного кода: без Spring и без Kafka</description>

    <dependencies>
        <dependency>
            <groupId>net.sizovs</groupId>
            <artifactId>pipelinr</artifactId>
        </dependency>
    </dependencies>
</project>
